### ISSUE TITLE
Add EventDispatcher 

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/test-support#4]
To determine if an event was triggered, we can add a simple EventDispatcher implementation

**Comment by viktorprogger** [comment]
@roxblnfk, WDYT about PhpUnit mock? It allows you to determine if an event was triggered and how many time it was triggered too. You can see an example [here](https://github.com/yiisoft/yii-queue/blob/f5b0a3020b63e389c43bcc0db4763629924d88f5/tests/unit/QueueTest.php#L56:L60).

**Comment by roxblnfk** [comment]
> @roxblnfk, WDYT about PhpUnit mock? It allows you to determine if an event was triggered and how many time it was triggered too. You can see an example [here](https://github.com/yiisoft/yii-queue/blob/f5b0a3020b63e389c43bcc0db4763629924d88f5/tests/unit/QueueTest.php#L56:L60).

Interesting, of course, but I don't think this code is intuitive
