### ISSUE TITLE
Add SimpleCache implementation

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/test-support#7]
I think it would be helpful to add a PSR [SimpleCache](https://www.php-fig.org/psr/psr-16/) implementation.
This Implementation should work like [ArrayCache](https://github.com/yiisoft/cache/blob/master/src/ArrayCache.php), but keeping and providing the history of operations

**Comment by samdark** [comment]
Is there currently a use-case for it?

**Comment by roxblnfk** [comment]
Why not?
- tested service requires a `CacheInterface` implementation. Pull ArrayCache? Create a mock (which may not match expected behavior)? Write custom stub?
- you need to test actions with the CacheInterface

**Comment by samdark** [comment]
> tested service requires a CacheInterface implementation

Which one? Is there any existing package that requires it?

**Comment by roxblnfk** [comment]
https://github.com/yiisoft/yii-cycle/blob/master/src/Schema/Provider/SimpleCacheSchemaProvider.php

**Comment by samdark** [comment]
OK.
